name: tomato_sentinel_example
description: Demonstrates how to use the tomato_sentinel plugin.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  tomato_sentinel:
    path: ../
  flutter_riverpod: ^2.4.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
